# Non-standard joint names:
#    - Create like this: controller_joint_names: [joint_1, joint_2, ... joint_N]
#    - This file will be loaded by abb_irb140_moveit_config/launch/moveit_planning_execution.launch
controller_joint_names: ['joint_1', 'joint_2', 'joint_3', 'joint_4', 'joint_5', 'joint_6']
